version: '2.1'
services:
  app:
    container_name: whiteboard
    command: python run.py

  tests-watch:
    extends:
      file: docker-compose.yml
      service: app
    container_name: whiteboard-tests
    command: ptw ./ -- -s

  tests:
    extends:
      file: docker-compose.yml
      service: app
    container_name: whiteboard-tests
    command: py.test tests